version: "3"

services:
  n8n:
    image: n8nio/n8n
    container_name: n8n
    restart: always
    env_file:
      - .env
    ports:
      - 5678:5678
    environment:
      - N8N_HOST=n8n.n8nbuilder.cc
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://n8n.n8nbuilder.cc/
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=<MY_USER>
      - N8N_BASIC_AUTH_PASSWORD=<MY_PASSWORD>
    volumes:
      - ./n8n-data:/home/node/.n8n
    networks:
      - ai_net

  ollama:
    image: ollama/ollama
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - ai_net

volumes:
  n8n_data:
  ollama_data:

networks:
  ai_net:
    driver: bridge
